"""add document ingestion and chunks

Revision ID: abeec2276831
Revises: c3e8b1f642a7
Create Date: 2026-07-16 06:45:31.043666

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "abeec2276831"
down_revision: str | None = "c3e8b1f642a7"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_versions",
        sa.Column(
            "file_size_bytes",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    op.alter_column(
        "document_versions",
        "file_size_bytes",
        server_default=None,
    )
    op.add_column(
        "document_versions",
        sa.Column("page_count", sa.Integer(), nullable=True),
    )
    op.add_column(
        "document_versions",
        sa.Column("extracted_character_count", sa.Integer(), nullable=True),
    )
    op.add_column(
        "document_versions",
        sa.Column("chunk_count", sa.Integer(), nullable=True),
    )
    op.add_column(
        "document_versions",
        sa.Column("processing_started_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "document_versions",
        sa.Column("processing_completed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "document_versions",
        sa.Column("failure_code", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "document_versions",
        sa.Column("failure_message", sa.Text(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_versions", "failure_message")
    op.drop_column("document_versions", "failure_code")
    op.drop_column("document_versions", "processing_completed_at")
    op.drop_column("document_versions", "processing_started_at")
    op.drop_column("document_versions", "chunk_count")
    op.drop_column("document_versions", "extracted_character_count")
    op.drop_column("document_versions", "page_count")
    op.drop_column("document_versions", "file_size_bytes")
    # ### end Alembic commands ###
